/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Banks: () => import('#controllers/banks_controller'),
  Bills: () => import('#controllers/bills_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Users: () => import('#controllers/users_controller'),
}
